name: WEEKLY

on:
  schedule:
    - cron:  '0 0 * * SAT'

jobs:
  build:
    strategy:
      matrix:
        BUILD_TYPE: [Release, Debug]
        DISTRO: ['fedora', 'fedora_rawhide', 'fedora_mpich', 'opensuse', 'ubuntu', 'ubuntu_devel', 'ubuntu_rolling', 'ubuntu_mpich']
        CXX: ['g++', 'clang++']
        include:
          - BUILD_TYPE: 'Debug'
            DISTRO: 'fedora_intel'
            CXX: 'icpc'
          - BUILD_TYPE: 'Debug'
            DISTRO: 'fedora_intel'
            CXX: 'icpx'

    runs-on: ubuntu-latest
    container: espressopp/buildenv:${{ matrix.distro }}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ${{ matrix.DISTRO }}-${{ matrix.CXX }}-${{ matrix.BUILD_TYPE }}-${{ github.run_id }}
          restore-keys: ${{ matrix.DISTRO }}-${{ matrix.CXX }}-${{ matrix.BUILD_TYPE }}

      - uses: actions/checkout@v2

      - name: Install Python Dependencies
        run: pip3 install -r requirements.txt

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.BUILD_TYPE }} -DCMAKE_CXX_COMPILER=${{ matrix.CXX }} -DESPP_WERROR=ON

      - name: Build
        run: cmake --build build --verbose --target all -j 2

      - name: Install
        run: cmake --install build

      - name: Test
        working-directory: build
        run: ctest --rerun-failed --output-on-failure -j 2
